### Word Embedding Techniques using Embedding Layer in Keras

In [1]:
### Libraries USed Tensorflow> 2.0  and keras

In [2]:
!pip install tensorflow-gpu

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 588.3/588.3 MB 2.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 439.2/439.2 KB 49.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 94.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.0/6.0 MB 112.3 MB/s eta 0:00:00
  Attempting uninstall: flatbuffers
    Found existing installation: flatbuffers 1.12
    Uninstalling flatbuffers-1.12:
      Successfully uninstalled flatbuffers-1.12
  Attempting uninstall: tensorflow-estimator
    Found existing installation: tensorflow-estimator 2.9.0
    Uninstalling tensorflow-estimator-2.9.0:
      Successfully uninstalled tensorflow-estimator-2.9.0
  Attempting uninstall: keras
    Found existing installation: keras 2.9.0
    Uninstalling keras-2.9.0:
      Successfully uninstalled keras-2.9.0
  Attempting uninstall: tensorboard
    Found existing 

In [3]:
import tensorflow as tf
print(tf.__version__)

2.11.0


In [4]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [5]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
### Vocabulary size
voc_size=500

#### One Hot Representation

In [10]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[70, 393, 462, 120], [70, 393, 462, 92], [70, 217, 462, 194], [16, 272, 417, 383, 470], [16, 272, 417, 383, 169], [174, 70, 113, 462, 312], [228, 211, 300, 383]]


### Word Embedding Represntation

In [11]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [12]:
import numpy as np

In [13]:
## pre padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0  70 393 462 120]
 [  0   0   0   0  70 393 462  92]
 [  0   0   0   0  70 217 462 194]
 [  0   0   0  16 272 417 383 470]
 [  0   0   0  16 272 417 383 169]
 [  0   0   0 174  70 113 462 312]
 [  0   0   0   0 228 211 300 383]]


In [14]:
## 10 feature dimesnions
dim=10


In [15]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [16]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             5000      
                                                                 
Total params: 5,000
Trainable params: 5,000
Non-trainable params: 0
_________________________________________________________________


In [17]:
##'the glass of milk',
embedded_docs[0]

array([  0,   0,   0,   0,  70, 393, 462, 120], dtype=int32)

In [18]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 73ms/step


array([[-0.00045891,  0.03191246,  0.01656177,  0.00143459,  0.04830951,
        -0.03945675, -0.00968158, -0.04749212,  0.03918058, -0.04794078],
       [-0.00045891,  0.03191246,  0.01656177,  0.00143459,  0.04830951,
        -0.03945675, -0.00968158, -0.04749212,  0.03918058, -0.04794078],
       [-0.00045891,  0.03191246,  0.01656177,  0.00143459,  0.04830951,
        -0.03945675, -0.00968158, -0.04749212,  0.03918058, -0.04794078],
       [-0.00045891,  0.03191246,  0.01656177,  0.00143459,  0.04830951,
        -0.03945675, -0.00968158, -0.04749212,  0.03918058, -0.04794078],
       [-0.01299606, -0.00713167,  0.0247088 , -0.04191135,  0.01323166,
         0.02434007, -0.02552849,  0.0326021 , -0.0160827 , -0.02481626],
       [ 0.04474229,  0.01753337,  0.01231567,  0.04562522, -0.03767314,
        -0.04059871,  0.04438558,  0.00059447,  0.0029129 ,  0.03363222],
       [ 0.04798   ,  0.03421644, -0.02202202, -0.0400816 , -0.01732289,
        -0.0011212 ,  0.00925682, -0.01679074

In [19]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 33ms/step
[[[-4.58907336e-04  3.19124572e-02  1.65617727e-02  1.43458694e-03
    4.83095087e-02 -3.94567475e-02 -9.68158245e-03 -4.74921241e-02
    3.91805805e-02 -4.79407795e-02]
  [-4.58907336e-04  3.19124572e-02  1.65617727e-02  1.43458694e-03
    4.83095087e-02 -3.94567475e-02 -9.68158245e-03 -4.74921241e-02
    3.91805805e-02 -4.79407795e-02]
  [-4.58907336e-04  3.19124572e-02  1.65617727e-02  1.43458694e-03
    4.83095087e-02 -3.94567475e-02 -9.68158245e-03 -4.74921241e-02
    3.91805805e-02 -4.79407795e-02]
  [-4.58907336e-04  3.19124572e-02  1.65617727e-02  1.43458694e-03
    4.83095087e-02 -3.94567475e-02 -9.68158245e-03 -4.74921241e-02
    3.91805805e-02 -4.79407795e-02]
  [-1.29960552e-02 -7.13167340e-03  2.47087963e-02 -4.19113524e-02
    1.32316612e-02  2.43400671e-02 -2.55284905e-02  3.26020978e-02
   -1.60827041e-02 -2.48162635e-02]
  [ 4.47422899e-02  1.75333731e-02  1.23156682e-02  4.56252210e-02
   -3.76731381e-02 -4.05987129e

In [20]:
embedded_docs[0]

array([  0,   0,   0,   0,  70, 393, 462, 120], dtype=int32)

In [21]:
print(model.predict(embedded_docs)[0])

1/1 [==============================] - 0s 16ms/step
[[-0.00045891  0.03191246  0.01656177  0.00143459  0.04830951 -0.03945675
  -0.00968158 -0.04749212  0.03918058 -0.04794078]
 [-0.00045891  0.03191246  0.01656177  0.00143459  0.04830951 -0.03945675
  -0.00968158 -0.04749212  0.03918058 -0.04794078]
 [-0.00045891  0.03191246  0.01656177  0.00143459  0.04830951 -0.03945675
  -0.00968158 -0.04749212  0.03918058 -0.04794078]
 [-0.00045891  0.03191246  0.01656177  0.00143459  0.04830951 -0.03945675
  -0.00968158 -0.04749212  0.03918058 -0.04794078]
 [-0.01299606 -0.00713167  0.0247088  -0.04191135  0.01323166  0.02434007
  -0.02552849  0.0326021  -0.0160827  -0.02481626]
 [ 0.04474229  0.01753337  0.01231567  0.04562522 -0.03767314 -0.04059871
   0.04438558  0.00059447  0.0029129   0.03363222]
 [ 0.04798     0.03421644 -0.02202202 -0.0400816  -0.01732289 -0.0011212
   0.00925682 -0.01679074  0.01742021 -0.00021775]
 [-0.03376792  0.0006673   0.02475241  0.04836084  0.00609164  0.00615267


In [22]:
### Assignment

sent=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]